require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrdosController do

  # This should return the minimal set of attributes required to create a valid
  # Ordo. As you add validations to Ordo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "label" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ordos as @ordos" do
      ordo = Ordo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ordos).should eq([ordo])
    end
  end

  describe "GET show" do
    it "assigns the requested ordo as @ordo" do
      ordo = Ordo.create! valid_attributes
      get :show, {:id => ordo.to_param}, valid_session
      assigns(:ordo).should eq(ordo)
    end
  end

  describe "GET new" do
    it "assigns a new ordo as @ordo" do
      get :new, {}, valid_session
      assigns(:ordo).should be_a_new(Ordo)
    end
  end

  describe "GET edit" do
    it "assigns the requested ordo as @ordo" do
      ordo = Ordo.create! valid_attributes
      get :edit, {:id => ordo.to_param}, valid_session
      assigns(:ordo).should eq(ordo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ordo" do
        expect {
          post :create, {:ordo => valid_attributes}, valid_session
        }.to change(Ordo, :count).by(1)
      end

      it "assigns a newly created ordo as @ordo" do
        post :create, {:ordo => valid_attributes}, valid_session
        assigns(:ordo).should be_a(Ordo)
        assigns(:ordo).should be_persisted
      end

      it "redirects to the created ordo" do
        post :create, {:ordo => valid_attributes}, valid_session
        response.should redirect_to(Ordo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ordo as @ordo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ordo.any_instance.stub(:save).and_return(false)
        post :create, {:ordo => { "label" => "invalid value" }}, valid_session
        assigns(:ordo).should be_a_new(Ordo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ordo.any_instance.stub(:save).and_return(false)
        post :create, {:ordo => { "label" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ordo" do
        ordo = Ordo.create! valid_attributes
        # Assuming there are no other ordos in the database, this
        # specifies that the Ordo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ordo.any_instance.should_receive(:update).with({ "label" => "MyString" })
        put :update, {:id => ordo.to_param, :ordo => { "label" => "MyString" }}, valid_session
      end

      it "assigns the requested ordo as @ordo" do
        ordo = Ordo.create! valid_attributes
        put :update, {:id => ordo.to_param, :ordo => valid_attributes}, valid_session
        assigns(:ordo).should eq(ordo)
      end

      it "redirects to the ordo" do
        ordo = Ordo.create! valid_attributes
        put :update, {:id => ordo.to_param, :ordo => valid_attributes}, valid_session
        response.should redirect_to(ordo)
      end
    end

    describe "with invalid params" do
      it "assigns the ordo as @ordo" do
        ordo = Ordo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ordo.any_instance.stub(:save).and_return(false)
        put :update, {:id => ordo.to_param, :ordo => { "label" => "invalid value" }}, valid_session
        assigns(:ordo).should eq(ordo)
      end

      it "re-renders the 'edit' template" do
        ordo = Ordo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ordo.any_instance.stub(:save).and_return(false)
        put :update, {:id => ordo.to_param, :ordo => { "label" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ordo" do
      ordo = Ordo.create! valid_attributes
      expect {
        delete :destroy, {:id => ordo.to_param}, valid_session
      }.to change(Ordo, :count).by(-1)
    end

    it "redirects to the ordos list" do
      ordo = Ordo.create! valid_attributes
      delete :destroy, {:id => ordo.to_param}, valid_session
      response.should redirect_to(ordos_url)
    end
  end

end
